#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# VibOps — Cold Install Script
#
# Installs VibOps on a fresh Linux VM (Ubuntu 22.04+ / Debian 12+).
# Requires: root or sudo, internet access, 4GB+ RAM, 20GB+ disk.
#
# Usage:
#   curl -fsSL https://vibops.ai/install.sh | bash
#
# Or with options:
#   bash install.sh --version 0.41.0 --llm-key sk-ant-xxx --admin-email admin@company.com
# ─────────────────────────────────────────────────────────────────────────────

VIBOPS_DIR="/opt/vibops"
VIBOPS_VERSION="${VIBOPS_VERSION:-0.41.1}"
LLM_API_KEY="${LLM_API_KEY:-}"
LLM_MODEL="${LLM_MODEL:-claude-sonnet-4-6}"
LLM_PROVIDER="${LLM_PROVIDER:-claude}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@vibops.local}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
COMPOSE_URL="https://vibops.ai/docker-compose.yml"

# ── Parse args ───────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case $1 in
    --version)      VIBOPS_VERSION="$2"; shift 2 ;;
    --llm-key)      LLM_API_KEY="$2"; shift 2 ;;
    --llm-model)    LLM_MODEL="$2"; shift 2 ;;
    --llm-provider) LLM_PROVIDER="$2"; shift 2 ;;
    --admin-email)  ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-password) ADMIN_PASSWORD="$2"; shift 2 ;;
    --dir)          VIBOPS_DIR="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Colours ──────────────────────────────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║           VibOps — Installation v${VIBOPS_VERSION}            ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── 1. Check prerequisites ──────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
  fail "This script must be run as root (use: sudo bash install.sh)"
fi

# ── 2. Install Docker if missing ─────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  warn "Docker not found — installing..."
  curl -fsSL https://get.docker.com | bash
  systemctl enable --now docker
  info "Docker installed"
else
  info "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
fi

if ! docker compose version &>/dev/null; then
  fail "Docker Compose v2 not found. Update Docker or install docker-compose-plugin."
fi
info "Docker Compose $(docker compose version --short)"

# ── 3. Create install directory ──────────────────────────────────────────────

mkdir -p "$VIBOPS_DIR"
cd "$VIBOPS_DIR"
info "Install directory: $VIBOPS_DIR"

# ── 4. Download docker-compose.yml ───────────────────────────────────────────

if [[ ! -f docker-compose.yml ]]; then
  curl -fsSL "$COMPOSE_URL" -o docker-compose.yml
  info "Downloaded docker-compose.yml"
else
  warn "docker-compose.yml already exists — keeping existing file"
fi

# ── 5. Generate .env ─────────────────────────────────────────────────────────

if [[ ! -f .env ]]; then
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  REDIS_PASSWORD=$(openssl rand -hex 24)
  SECRET_KEY=$(openssl rand -hex 32)
  JWT_SECRET_KEY=$(openssl rand -base64 32)
  VAULT_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || openssl rand -base64 32)
  INTERNAL_API_KEY=$(openssl rand -hex 32)
  GRAFANA_PASSWORD=$(openssl rand -base64 16)

  if [[ -z "$ADMIN_PASSWORD" ]]; then
    ADMIN_PASSWORD=$(openssl rand -base64 12)
    warn "Generated admin password: $ADMIN_PASSWORD (save this!)"
  fi

  # Generate AUTH_PASSWORD_HASH (PBKDF2-SHA512, salt:hash hex)
  AUTH_PASSWORD_HASH=$(python3 -c "
import hashlib, os
salt = os.urandom(16)
h = hashlib.pbkdf2_hmac('sha512', '${ADMIN_PASSWORD}'.encode(), salt, 100000)
print(salt.hex() + ':' + h.hex())
")

  cat > .env <<ENVEOF
# VibOps — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# ─── Version ────────────────────────────────────────────────
VIBOPS_VERSION=${VIBOPS_VERSION}

# ─── Database ───────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://vibops:${POSTGRES_PASSWORD}@postgres:5432/vibops_db

# ─── Redis ──────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}

# ─── Security ───────────────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
VAULT_KEY=${VAULT_KEY}
INTERNAL_API_KEY=${INTERNAL_API_KEY}

# ─── Auth ───────────────────────────────────────────────────
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
AUTH_USERNAME=admin
AUTH_PASSWORD_HASH=${AUTH_PASSWORD_HASH}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_EXPIRE_HOURS=24

# ─── LLM ────────────────────────────────────────────────────
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
LLM_API_KEY=${LLM_API_KEY}
LLM_BASE_URL=

# ─── App ────────────────────────────────────────────────────
APP_ENV=production

# ─── Webhooks (generated, override if needed) ───────────
GITHUB_WEBHOOK_SECRET=$(openssl rand -hex 32)
GRAFANA_WEBHOOK_SECRET=$(openssl rand -hex 32)

# ─── Grafana ────────────────────────────────────────────────
GRAFANA_PUBLIC_URL=http://localhost:3000
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# ─── SMTP (optional) ────────────────────────────────────────
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=noreply@yourcompany.com

# ─── Reverse proxy ──────────────────────────────────────────
VIBOPS_DOMAIN=:80

# ─── Internal URLs ──────────────────────────────────────────
CORE_API_URL=http://core:8000
AGENT_API_URL=http://agent:8001
ENVEOF

  chmod 600 .env
  info "Generated .env with secure random secrets"
else
  warn ".env already exists — keeping existing configuration"
fi

# ── 6. Pull images ───────────────────────────────────────────────────────────

info "Pulling VibOps images (v${VIBOPS_VERSION})..."
docker compose pull --quiet 2>/dev/null || docker compose pull
info "All images pulled"

# ── 7. Start services ───────────────────────────────────────────────────────

info "Starting VibOps..."
docker compose up -d

# ── 8. Wait for healthy ─────────────────────────────────────────────────────

echo -n "Waiting for Core API to be healthy"
for i in $(seq 1 60); do
  if docker compose exec -T core python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health')" &>/dev/null; then
    echo ""
    info "Core API is healthy"
    break
  fi
  echo -n "."
  sleep 2
done

# ── 9. Run migrations ───────────────────────────────────────────────────────

info "Running database migrations..."
docker compose exec -T core alembic upgrade head
info "Migrations complete"

# ── 10. Summary ──────────────────────────────────────────────────────────────

SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              VibOps is running!                     ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  Console:    http://${SERVER_IP}:8003                ║"
echo "║  Core API:   http://${SERVER_IP}:8000                ║"
echo "║  Grafana:    http://${SERVER_IP}:3000                ║"
echo "║                                                      ║"
echo "║  Admin:      ${ADMIN_EMAIL}                          ║"
echo "║  Config:     ${VIBOPS_DIR}/.env                      ║"
echo "║  Logs:       docker compose -f ${VIBOPS_DIR}/docker-compose.yml logs -f ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

if [[ -z "$LLM_API_KEY" ]]; then
  warn "LLM_API_KEY is empty — the agent will not work until you set it in ${VIBOPS_DIR}/.env and restart:"
  echo "  docker compose -f ${VIBOPS_DIR}/docker-compose.yml restart agent"
fi

info "Installation complete"
